/* テーブル作成用のsql */

/* テーブルの削除 */
DROP TABLE IF EXISTS transaction_detail_t;
DROP TABLE IF EXISTS transaction_t;
DROP TABLE IF EXISTS order_detail_t;
DROP TABLE IF EXISTS order_t;
DROP TABLE IF EXISTS notice_t;
DROP TABLE IF EXISTS close_t;
DROP TABLE IF EXISTS custom_m;
DROP TABLE IF EXISTS set_goods_m;
DROP TABLE IF EXISTS goods_m;
DROP TABLE IF EXISTS user_m;

/* ユーザマスタの定義 */
CREATE TABLE IF NOT EXISTS user_m(
    mail VARCHAR(50) PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(2) NOT NULL,
    member_rank VARCHAR(6) NOT NULL,
    gender VARCHAR(2) NOT NULL,
    birthday DATE NOT NULL,
    cancel_count INT NOT NULL,
    alive BOOLEAN NOT NULL DEFAULT FALSE,
    point INT NOT NULL DEFAULT 0,
    point_card_complete INT NOT NULL DEFAULT 0
);

/* 商品マスタの定義 */
CREATE TABLE IF NOT EXISTS goods_m(
    goods_id INT PRIMARY KEY,
    goods_name VARCHAR(50) NOT NULL,
    photo VARCHAR(100),
    price INT NOT NULL,
    calorie INT,
    allergy VARCHAR(50),
    zangi_count INT NOT NULL,
    sold_out BOOLEAN NOT NULL DEFAULT FALSE,
    detail VARCHAR(100),
    watch_rank VARCHAR(6) NOT NULL DEFAULT '一般'
);

/* セット商品マスタ */
CREATE TABLE IF NOT EXISTS set_goods_m(
    set_goods_id INT PRIMARY KEY,
    goods_name VARCHAR(50) NOT NULL,
    price INT NOT NULL,
    calorie INT,
    allergy VARCHAR(50),
    sold_out BOOLEAN NOT NULL DEFAULT FALSE
);

/* カスタムマスタの定義 */
CREATE TABLE IF NOT EXISTS custom_m(
    custom_id INT PRIMARY KEY,
    gooods_name VARCHAR(50) NOT NULL,
    price INT NOT NULL,
    calorie INT,
    allergy VARCHAR(50)
);

/* 休業日トランの定義 */
CREATE TABLE IF NOT EXISTS close_t(
    close_day DATE PRIMARY KEY,
    close_type VARCHAR(4) NOT NULL
);

/* 通知トランの定義 */
CREATE TABLE IF NOT EXISTS notice_t(
    notice_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mail VARCHAR(50) NOT NULL REFERENCES user_m(mail),
    register_time DATETIME NOT NULL,
    content VARCHAR(100) NOT NULL
);

/* 注文トランの定義 */
CREATE TABLE IF NOT EXISTS order_t(
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(5) NOT NULL,
    get_time DATETIME NOT NULL,
    mail VARCHAR(50) NOT NULL REFERENCES user_m(mail),
    register_time DATETIME NOT NULL,
    sum_money INT NOT NULL,
    memo VARCHAR(2) NOT NULL,
    status VARCHAR(5) NOT NULL DEFAULT '受付'
);

/* 注文明細トランの定義 */
CREATE TABLE IF NOT EXISTS order_detail_t(
    order_id INT PRIMARY KEY REFERENCES order_t(order_id),
    order_count INT PRIMARY KEY NOT NULL,
    goods_id INT NOT NULL REFERENCES goods_m(goods_id),
    set_goods_id INT REFERENCES set_goods_m(set_goods_id),
    count INT NOT NULL,
    plus_zangi_count INT NOT NULL DEFAULT 0,
    custom_id INT REFERENCES custom_m(custom_id)
);

/* 取引トランの定義 */
CREATE TABLE IF NOT EXISTS transaction_t(
    transaction_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL REFERENCES order_t(order_id),
    mail VARCHAR(50) NOT NULL REFERENCES user_m(mail),
    transaction_date DATETIME NOT NULL,
    use_coupon VARCHAR(9),
    received_money INT NOT NULL,
    change_money INT NOT NULL,
    sum_money INT NOT NULL
);

/* 取引明細トランの定義 */
CREATE TABLE IF NOT EXISTS transaction_detail_t(
    transaction_id INT PRIMARY KEY REFERENCES transaction_t(transaction_id),
    reservation_count INT PRIMARY KEY NOT NULL,
    goods_name VARCHAR(50) NOT NULL,
    set_goods_name VARCHAR(50),
    count INT NOT NULL,
    plus_zangi_count INT NOT NULL DEFAULT 0,
    custom_id INT REFERENCES custom_m(custom_id),
    price INT NOT NULL,
);