# アプリケーション名
spring.application.name=polestar

# サーバーポート設定（デフォルトは 8080）
server.port=8080

# 文字コード設定 (UTF-8)
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true