# アプリケーション名
spring.application.name=polestar

# サーバーポート設定（デフォルトは 8080）
server.port=8080

# 文字コード設定 (UTF-8)
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# DB設定
## 共通
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/data.sql
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/portallink
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=portallink

# プロファイル状態（dev:開発環境/prod:本番環境）
spring.profiles.active=dev

# ログインデバッグ用
# logging.level.org.springframework.security=DEBUG